#! /usr/bin/bash 

echo "enter the name of the new database"
read n
flag=$(. ./checkIfdbExists $n)

if [ $flag == 0 ]; then
	echo "This name already exists "
	. ./CreateDB
else 
       mkdir ./databases/$n
       echo "database created successfully"
fi
